#pragma once

enum OBJECT_TYPE
{
	OBJECT_BACKGROUND, OBJECT_MONSTER,OBJECT_ITEM, OBJECT_PLAYER, OBJECT_MOUSE, OBJECT_END
};
enum ITEM_TYPE
{
	ITEM_WEAPON,ITEM_ARMOR,ITEM_GOLD,ITEM_END
};

enum ANIMATION_TYPE
{
	ANIMATION_ONCE,ANIMATION_LOOP,ANIMATION_END
};

enum SCENE_NAME
{
	SCENE_TITLE,SCENE_MENU,SCENE_EDIT,SCENE_STAGE,SCENE_END
};